### ISSUE TITLE
Create the 'all' command

### ISSUE THREAD

**Issue by benjmarshall** [the-heap/beacon#15]
I have created a branch 'print_all_command' to put together some code to show how the all command can be added. This branch also refactors some of the existing functionality (log loading) into it's own function and removes the global log data variable.

I am not sure about creating a PR for this yet as I have branched from the 'write_to_file' branch in order to take the existing switch case based argument parsing approach. Perhaps it is best to wait until #12 has been merged into master before creating a PR?

**Comment by teesloane** [comment]
Excellent.

I'll merge what we have of #12 today to keep your branch from rotting. Even though `write-to-file` functionality doesn't exist, we will return to it shortly.

**Comment by teesloane** [comment]
Merged! you should be good to make a PR.

**Comment by benjmarshall** [comment]
PR #16  created for review.

**Comment by benjmarshall** [comment]
PR #16 Merged.
