### ISSUE TITLE
Create a Beacon Log package

### ISSUE THREAD

**Issue by benjmarshall** [the-heap/beacon#17]
All data types and functionality related to the beacon log file should be moved into it's own package. This will help to reduce clutter in the main executable file and make it easier to develop unit tests.

**Comment by jbydeley** [comment]
Just to be clear, do you mean a new directory with a new `package` namespace or just a new file within the `package main` namespace and root folder?

**Comment by benjmarshall** [comment]
I think the 'Go' way of doing it would be do have a subdirectory with a new package namespace.

I can move the existing functionality over to this setup and see what people think.

**Comment by teesloane** [comment]
I do not have much input on this - don't really know when something should be a package in go or should just be another file.

Why don't we just go by packages, and then can change it as needed until we figure out the most idiomatic `Go` way to do it? 

Labelled as refactoring and referenced in #14

**Comment by benjmarshall** [comment]
I have created a new branch for this - 'create_beacon_log_package'.

You can pull this now and see what I have done in creating the package.

There are a couple of things to discuss here, first is the LoadLog function. This currently returns a new BeaconLog type, which for the current level of functionality is fine. It would probably be more idiomatic for this function to become a method on an existing BeaconLog struct. This would also allow more flexibility in the handling going forwards, for example if we have already created a new local BeaconLog struct with some entries but we need to load existing entries from a file.

Alternatively we could change this to be a 'NewFromFile()' function which still creates a new BeaconLog struct and returns it. Now i'm considering this I think it could be the best solution. You can still use the normal method of creating a blank BeaconLog struct, but a special 'New' function which loads from a file sounds sensible. In my mind the existing LoadLog function name would be better associated with something that populated an existing struct from the file contents rather than creating a new struct.

Hopefully that makes sense and isn't too rambling!

The second thing is the PrintLog function. The more idiomatic way of implementing this functionality is to implement the 'Stringer' interface  (https://tour.golang.org/methods/17) by providing a string() method on the BeaconLog type. This would look very similar to PrintLog() but will return a string. Doing this allows the main function to then print the log to terminal using `fmt.Println(beaconLogData)`.

I will implement this next as I think the first point above needs more discussion.

**Comment by teesloane** [comment]
Excellent! There is a currently a PR for refactoring `beaconConfig` into a package and should be merged soon. 

Some thoughts:

I think I follow; I'm still grokking structs + methods on structs (interfaces, I guess?). AS I see, there are two proposed ways of handling a refactor that better addresses how beacon handles an in memory struct (one that is to be created and written from file) and also the beacon logs that have been loaded from files. 

For now, regarding the proposed refactor, I suggest we wait until we have both:
- this refactor done (ie. moving out all log related functionality into a new package. This will make further refactoring easier
- we have the ability to write to the file. We are still missing this core functionality; I think it would be wise to have it working first while we ponder away.

All in all, great stuff! I'm excited to see the PR for putting the Log file into it's own package. 💯

**Comment by benjmarshall** [comment]
PR #24 created to cover this issue.

I have started a basic tests file for this package but we need further discussion on the implementation of the LoadLog() function. I think it is more idiomatic (and easier for testing) if this function takes a Reader interface. This would mean that main.go would become responsible for actually opening the file (and checking no errors occured) and passing an io.reader into LoadLog(). It would also mean that for testing we can create a Reader interface from a string or byte array instead of creating extra test files. This discussion also impacts the config package  from @jbydeley as it has similar loading functionality and currently uses extra files for testing. Let me know what you think!

**Comment by teesloane** [comment]
Excellent work on the PR @benjmarshall.

This is starting to get into territory with Go where I am more unfamiliar and would leave this discussion up to you and @jbydeley. Regardless, I will do some reading to learn about Reader interfaces. 

I'm not sure how big a change that would be (sounds fairly small).

I like the sound of more idiomatic Go and easier tests; but I also want to make sure that we get core functionality done before doing too much more refactoring — we are almost done #14 — I'm going to close it when I merge #24 ... and then I'll open a new PR for a `refactor pt 2` to do after more core stuff is written — and we can get a nice checklist going.

**Comment by teesloane** [comment]
#24 merged!
