### ISSUE TITLE
Change beaconlog's date to a timestamp

### ISSUE THREAD

**Issue by jbydeley** [the-heap/beacon#23]
Currently we're saving just a `2017/01/20` style date. Changing this to a unix timestamp would allow us to format it later and allow us to include time in our display (if needed). Go has some built in formats that look pretty nice. https://golang.org/pkg/time/#pkg-constants

**Comment by teesloane** [comment]
Great - we looked into this but couldn't figure out datetimes and how to handle them yet for Go. Let's get into it when we fix up writing to file #4

**Comment by jbydeley** [comment]
Sure. I have a solution for writing to the file. It's based on the work @benjmarshall has in his branch.

**Comment by teesloane** [comment]
Great! we just merged #24 and this should be good to go next!

**Comment by teesloane** [comment]
Closed in #30
