### ISSUE TITLE
Naming things

### ISSUE THREAD

**Issue by teesloane** [the-heap/beacon#28]
Being new to Go I'm not super familiar with naming conventions. I do understand that `Capitlized` things get exported (I like this).

I'm curious about naming packages, and to a lesser extent, variables.
From the javascript world, I'm pretty familiar with `camelCase` vars. 

It appears, from the [docs](https://golang.org/doc/effective_go.html#mixed-caps) that mixed caps is the way to go. So let's aim for that.

As for package naming, I'm conflicted and not sure how to go about this. Here's some code for example:

```
package messagelog

type Log struct {
     // ....
}

func Save () { ... }

func LoadLog () { ... }

```

So here, we'll be using `messagelog.Log` for every type instance right?
If we were to change the package to `message` or `messages` ... we would require `message.Log` ... 

so is that cleaner?

Well, when it comes time to `Save` a message we get,

`message.Save` -- that looks nice and sounds good to me,

but when we go to `LoadLog`

`message.LoadLog` doesn't really sound so great; 
`messages.LoadLog` -> sounds a bit better.

Any thoughts on this? Naming, as usual, is hard. 

Feel free to also mention any other var/package names that we should reconsider as we go forward. To me, terminology and jargon (and the way we select the words to describe our product) are very important. It's a big part of making sure both the people working on the project and the users can hit the ground running / make good use of the tool.

**Comment by jbydeley** [comment]
@teesloane @benjmarshall I created a branch that has a large number of refactors based on this and a few other issues where we've talked about refactoring. I may have gone too far so I don't mind throwing it away but figured I'd link it here and if you want a PR I can do that. It should at least create some discussion points around the refactoring.

[Big Refactor](https://github.com/jbydeley/beacon/tree/big_refactor)

**Comment by teesloane** [comment]
@jbydeley 

Overall this looks great. I don't think we need to throw any of it away; everything is looking useful and good. Can you make a PR? I like the `Show` method. It makes sense. I think we should have a default `beacon` command that just displays `x` most recent entries, but other than that this is good. I think we can have multiple flags that kind of do the same thing.

We are quickly approaching a useable MVP 0.1. We still need to handle `beacon init` ( #20 ), but other than that I will open an issue for discussing MVP 0.2; which will eventually yield a roadmap checklist. 

Great work so far peeps.

**Comment by jbydeley** [comment]
Sounds good, I'll open a PR then.

**Comment by teesloane** [comment]
Great, thanks!

**Comment by teesloane** [comment]
Closing this, any other information related to naming things should eventually be mentioned in some kind of docs file..
