### ISSUE TITLE
create .beaconrc file

### ISSUE THREAD

**Issue by teesloane** [the-heap/beacon#3]
I'm not sure what the protocol is with creating `.rc` files, but here are some configuration options we could benefit from:

- if we're using local files allow a user to set their `sync folder path` ; ie. if your team is using dropbox to sync the Beacon change log, then any user with a non-standard dropbox folder path, will have issues.

**Comment by benjmarshall** [comment]
I haven't really seen any standardised methods of allowing local user configuration for Go applications yet.

For configuration of application build for dev/production etc it seems common to use YAML or TOML files to load config information into a config struct, but I'm not sure this is the right approach here.

I have come across https://github.com/shibukawa/configdir which I recently used to store a high score file for a basic game in a cross-platform way. Perhaps using the same approach to store a plain text .beaconrc file would be appropriate (and cross-platform!).

Alternatively we could use the library above and store a JSON format config file. The user could set config options through a subcommand of the beacon cli, e.g.:
`beacon --set-config sync_folder_path '/home/ben/dropbox/beacon_log.json'`

I'm happy to have a look at this.

**Comment by teesloane** [comment]
Thanks for tackling this @benjmarshall . I'm not sure how to handle this quite yet -- in fact this issue was opened with having completed the more basic stuff in mind (like reading and writing to the beacon_log). But please do look into it; I think having this sort of like a `.gitignore` or a `.eslintrc` (i'm from the javascript world) in a project directory could be a neat way to have this work. 

I think my original conception of this idea (the `beaconrc` file) I was thinking of having something like dropbox play an integral role in the beacon_log file. 

But... perhaps we should just use git - it's standardized, it's powerful; and what we're building here -- well it would be (sort of) obsolete if people wrote more specific git commit messages / if there wasn't so much information to grep through on large teams

Perhaps going forward, there will still be a need for a configuration file but we don't know for what exactly yet. 

Now that i'm thinking of ditching a sync'ing folder (ie dropbox); I think we'd have to move more in the direction of using git-hooks to trigger the usage of Beacon. For example:

- a user makes a change to a db-migration (in their `migrations` folder to keep it simple)
- when going to commit their change, somehow Beacon can detect that it needs to capture a breaking change
- Beacon prompts a user to log their change.

so in this case, we would still need a configuration file for Beacon to know what folders to watch. 

Does any of that make sense? I'm still waking up.

**Comment by benjmarshall** [comment]
I think your making sense yes. Keeping the functionality local to git rather than relying on a 3rd party file sharing service certainly makes sense.

I do like the idea that beacon could be automatically triggered for the appropriate git actions, taking the responsibility away from the user slightly.

Some issues which strike me straight off are:

- Log file is now going to be under git source control so will have to be subject to merging etc just like any other source. Will this create problems when merging two branches each with their own 'breaking changes'.
- In order to know about the latest 'breaking changes' a user will have to regularly pull from the latest dev or master branch to know about anything merged by other contributors. (Although it strikes me that if a branch is flagged as having breaking changes then this should be reviewed at the PR stage and appropriate updates issued to all contributors?)

Edit: Perhaps you are also correct in saying this is an issue worth coming back to when the basic functionality is in place and we have a better idea of the use cases and user stories for the tool. I suggest we return to this issue when more of the basic items on the roadmap have been ticked off - certainly after we have settled on cli commands and arguments, and can reliably read/write and update a log file through the cli tool.

**Comment by teesloane** [comment]
You bring up some good points regarding git and how to keep this file from having information wiped / altered in merge conflicts. I also want to be careful that people don't look at this file and just say : "why don't you use git?" or "that's what git is for". I suppose the point is, that we want to tackle a relatively niche challenge — communication on big changes. 

I think beacon should serve a sort of "source of truth" for devs — and only _the most important_ information should go into it. Of course the user can use it however they like. 


>In order to know about the latest 'breaking changes' a user will have to regularly pull from the latest dev or master branch to know about anything merged by other contributors.

I think this is ok — there are often times on big teams when several PR's are merged in the span or say, two or three days, before you yourself as a dev come back to that repo. When the time comes and you pull master (maybe, say, 5 merges), you can scan beacon and see if any the changes require action. I suppose just having git display the files that have changed on add (like, the columns of green `+` and red `-` would be useful if you saw that next to your beacon file — an immediate indicator of something needing attention.

But yes, let's come back to this in time. I will leave this issue open and label it as a "nice to have" or something like that.

**Comment by jbydeley** [comment]
Replying here based on @teesloane 's comments over [here](https://github.com/the-heap/beacon/issues/11#issuecomment-321428823).

> 
> Sounds excellent @jbydeley
> Do you have any interest in tackling this over in this issue?. I'd love for you to tackle some or all of this feature if you are up for it.
> 
> There has been some coinciding talk with @benjmarshall as well; and this conversation is starting to stray toward that issue I believe. Here are some questions I have that perhaps you can address:
> 
>     

> - [ ] can we list the advantages of TOML over a json file or .beacon_rc file?
>     example: Golang has parsing built in for Json — but not toml. I want to avoid using unecessary packages if able. What would make toml more powerful / a better choice?
> - [ ] what information can we put in a toml / json file? What is the minimum? what is nice to know?

| Benefit | JSON | TOML |
| - | - | - |
| Standard Format | Yes | Yes |
| Easy to understand | Yes | Yes |
| Permits Comments | No | Yes |
| Diffs Neatly | No | Yes |
| Built into the Std library | Yes | No |

I can build it using either format. I do like comments in config files to help grok things. Also allows you to comment that something is required or not. In our case it might be overkill but I'm easy. Whatever works.

My MVP for this would be author name and email. We can bolt on additional things if we want (maybe I prefer seeing the last 10 breaking changes or the last 1 day of breaking changes).

**Comment by teesloane** [comment]
Thanks for adding your 2 cents over here @jbydeley 

Here are some thoughts off the top of my head (might get a bit long haha)

TOML certainly wins when it comes to most use cases (I do agree it reads nicely, and I often am sad at not being able to comment in json files). Right now I'm still fairly new to Golang and so my hesitancy with using 3rd party packages is mostly:

- my inability to inform people how to use them
- choosing the "right" vendor tool (I know there are several)
- blocking people from getting started because they have to install _yet another tool_ etc (altho is is perhaps a petty point

My initiative for running a project with "no/few 3rd party packages" kind of caters to the above / my ego with not knowing things ;). The reason I lean toward JSON (I might be repating myself):

- it's so common, you're going to need to learn it anyway (and I personally want to learn how Go handles it)
- we're already going to be doing it for the log file
- we should avoid 3rd party packages so we can learn more about the stdlib
- similarly, we don't have to rely on a 3rd party package being up to date as Go evolves (this is highly unlikely to be a problem, but I come from a javascript background where it is... and I am more presently aware of such things.)
- it may be able to integrate with the notion of a `beaconrc` file (discussed later below)

Thoughts? Should we build in JSON and consider refactoring to toml later if time permits us? should we write our own toml parser?! (kidding....), should we parse plain text from a `.beaconrc` ? 

***

side note, I just read [this thread](https://stackoverflow.com/questions/36212256/what-are-rc-files-in-nodejs) to learn more about what RC files are. It seems like we could have one, and just format it as json...  so this is yet another option. The one thing I like about `rc` files is that (to me) there is a sort of association of 

>Usually, they're useful for some sort of tool that acts on your source code and needs some tuning specific to your project. 

as the thread author pointed out. 

With `rc` files, I also associate the idea of "this is a settings file"; they are also hidden by file systems naturally which is a good thing I think. 

I think ideally, maybe we can try creating a json file but storing it in a `beaconrc` file and see what happens.

**Comment by jbydeley** [comment]
I created a PR #13. It uses the .beaconrc file in JSON format. For kicks, I created a TOML solution as well. I think it wouldn't be difficult to transition to TOML if we ever feel the need though I think it's overkill for sure.

**Comment by teesloane** [comment]
This has been assessed (so quickly too!) in #13. Closing until further notice :)

🚢 🚢 🚢
