### ISSUE TITLE
Users can write to the beacon_log

### ISSUE THREAD

**Issue by teesloane** [the-heap/beacon#4]
Note: This issue is similar to #2  (setting up a basic read file in Go).

**Overview**

User's need to be able to manually append / add to the `Beacon Log`. 

**Example use case**

A user runs a migration on their database.  After committing their code they can run a command from the terminal that allows them to write an update for this breaking change. A user should be able to do that and be prompted by the CLI for each piece of text they need to add (author, message etc).

**Minimum requirements:**
- [x] A user can run `beacon add "this is a breaking change log message" 
- [x] The message text is used to create a struct of type `Log` (pulling other values for Log out of a `.beaconrc`; ie -> user name, email)
- [x] The struct is marshalled as json and appended to the `logs` key in the beacon_log.json` file.

**Goals:**

- learn how prompts work on the cli
- learn how to marshal json

**Stretch goals (future issues / ideas )**

- Writing to this file should be triggered by being able to watch certain directories so that a user is automagically prompted to fill in a log (ie. whenever something changes in the `/migrations/` folder
- Beacon can auto remember a user's name / creds; like Git; ie. they don't need to type in their name for the message author every time Beacon is used

**Comment by broneks** [comment]
I'll give this a go ;)

**Comment by teesloane** [comment]
Awesome!

Keep us in the loop, happy to see some progress with PRs even if it's not shippable right away!

**Comment by teesloane** [comment]
please note that there has been some great conversation on structuring human-computer interfacing with Beacon in #11
