### ISSUE TITLE
Project Setup Guidelines have wrong run command in README.md

### ISSUE THREAD

**Issue by benjmarshall** [the-heap/beacon#7]
In README.md the section Project Setup Guidelines specify to execute: `Run main.go`.

This is not a valid command and should be `go run main.go`.

Edit: I'll fork and create a branch to update this and submit a PR shortly.

**Comment by teesloane** [comment]
Just [merged](https://github.com/the-heap/beacon/pull/8) ! Thanks @benjmarshall !
